import '../models/app_classification.dart';

// Default app categorizations by package name.
// Users can override these in Settings.
class DefaultCategories {
  /// Human-readable display names for known package names.
  /// Used as a fallback when the system cannot resolve the app label.
  static const Map<String, String> displayNames = {
    'com.ichi2.anki': 'AnkiDroid',
    'org.ankidroid.anki': 'AnkiDroid',
    'com.instructure.candroid': 'Canvas Student',
    'com.zwift.android': 'Zwift',
    'com.duolingo': 'Duolingo',
    'com.google.android.apps.fitness': 'Google Fit',
    'com.strava': 'Strava',
    'com.calm.android': 'Calm',
    'com.headspace.android': 'Headspace',
    'com.audible.application': 'Audible',
    'com.wunderlist.android': 'Wunderlist',
    'com.todoist': 'Todoist',
    'com.notion.id': 'Notion',
    'com.evernote': 'Evernote',
    'org.khanacademy.android': 'Khan Academy',
    'com.coursera.android': 'Coursera',
    'com.memrise.android.memrisecompanion': 'Memrise',
    'com.babbel.mobile.android.en': 'Babbel',
    'com.rosettastone.mobile.courseware': 'Rosetta Stone',
    'com.linguee': 'Linguee',
    'com.peloton.android': 'Peloton',
    'com.nike.ntc': 'Nike Training Club',
    'com.alltrails.alltrails': 'AllTrails',
    'com.clozemaster': 'Clozemaster',
    'com.readdle.smartmailapp': 'Spark',
    'com.zhiliaoapp.musically': 'TikTok',
    'com.ss.android.ugc.trill': 'TikTok',
    'com.instagram.android': 'Instagram',
    'com.facebook.katana': 'Facebook',
    'com.twitter.android': 'Twitter',
    'com.x.android': 'X',
    'com.reddit.frontpage': 'Reddit',
    'com.snapchat.android': 'Snapchat',
    'com.pinterest': 'Pinterest',
    'com.tumblr': 'Tumblr',
    'com.zhiliaoapp.musically.go': 'TikTok Lite',
    'com.vkontakte.android': 'VK',
    'com.bytedance.tiktok': 'TikTok',
    'com.king.candycrushsaga': 'Candy Crush Saga',
    'com.supercell.clashofclans': 'Clash of Clans',
    'com.supercell.clashroyale': 'Clash Royale',
    'com.rovio.angrybirds': 'Angry Birds',
    'com.nianticlabs.pokemongo': 'Pokémon GO',
    'com.playrix.gardenscapes': 'Gardenscapes',
    'com.ea.game.pvzfree_row': 'Plants vs. Zombies',
    'com.kiloo.subwaysurf': 'Subway Surfers',
    'com.imangi.templerun': 'Temple Run',
    'com.google.android.apps.maps': 'Google Maps',
    'com.spotify.music': 'Spotify',
    'com.google.android.apps.youtube.music': 'YouTube Music',
    'com.apple.android.music': 'Apple Music',
    'com.whatsapp': 'WhatsApp',
    'com.google.android.apps.messaging': 'Google Messages',
    'com.android.dialer': 'Phone',
    'com.google.android.gm': 'Gmail',
    'com.microsoft.outlook': 'Outlook',
    'com.google.android.calendar': 'Google Calendar',
    'com.weather.Weather': 'Weather',
    'com.yahoo.mobile.client.android.weather': 'Yahoo Weather',
    'com.google.android.apps.photos': 'Google Photos',
    'com.google.android.apps.docs': 'Google Docs',
    'com.netflix.mediaclient': 'Netflix',
    'com.amazon.avod.thirdpartyclient': 'Prime Video',
    'com.hulu.plus': 'Hulu',
    'com.disney.disneyplus': 'Disney+',
    'com.google.android.youtube': 'YouTube',
    'com.slack': 'Slack',
    'com.microsoft.teams': 'Microsoft Teams',
    'us.zoom.videomeetings': 'Zoom',
    'com.skype.raider': 'Skype',
    'org.telegram.messenger': 'Telegram',
    'com.discord': 'Discord',
  };

  static const Map<String, AppCategory> defaults = {
    // === GOOD APPS (educational, health, productivity) ===
    'com.ichi2.anki': AppCategory.good,
    'org.ankidroid.anki': AppCategory.good,
    'com.instructure.candroid': AppCategory.good,       // Canvas
    'com.zwift.android': AppCategory.good,              // Zwift
    'com.duolingo': AppCategory.good,
    'com.google.android.apps.fitness': AppCategory.good, // Google Fit
    'com.strava': AppCategory.good,
    'com.calm.android': AppCategory.good,
    'com.headspace.android': AppCategory.good,
    'com.audible.application': AppCategory.good,
    'com.wunderlist.android': AppCategory.good,
    'com.todoist': AppCategory.good,
    'com.notion.id': AppCategory.good,
    'com.evernote': AppCategory.good,
    'org.khanacademy.android': AppCategory.good,
    'com.coursera.android': AppCategory.good,
    'com.memrise.android.memrisecompanion': AppCategory.good,
    'com.babbel.mobile.android.en': AppCategory.good,
    'com.rosettastone.mobile.courseware': AppCategory.good,
    'com.linguee': AppCategory.good,
    'com.peloton.android': AppCategory.good,
    'com.nike.ntc': AppCategory.good,                   // Nike Training
    'com.alltrails.alltrails': AppCategory.good,
    'com.clozemaster': AppCategory.good,
    'com.readdle.smartmailapp': AppCategory.good,

    // === BAD APPS (infinite scroll, high dopamine) ===
    'com.zhiliaoapp.musically': AppCategory.bad,        // TikTok
    'com.ss.android.ugc.trill': AppCategory.bad,        // TikTok (alt)
    'com.instagram.android': AppCategory.bad,
    'com.facebook.katana': AppCategory.bad,
    'com.twitter.android': AppCategory.bad,
    'com.x.android': AppCategory.bad,                   // X / Twitter
    'com.reddit.frontpage': AppCategory.bad,
    'com.snapchat.android': AppCategory.bad,
    'com.pinterest': AppCategory.bad,
    'com.tumblr': AppCategory.bad,
    'com.zhiliaoapp.musically.go': AppCategory.bad,
    'com.vkontakte.android': AppCategory.bad,
    'com.bytedance.tiktok': AppCategory.bad,
    'com.king.candycrushsaga': AppCategory.bad,
    'com.supercell.clashofclans': AppCategory.bad,
    'com.supercell.clashroyale': AppCategory.bad,
    'com.rovio.angrybirds': AppCategory.bad,
    'com.nianticlabs.pokemongo': AppCategory.bad,
    'com.playrix.gardenscapes': AppCategory.bad,
    'com.ea.game.pvzfree_row': AppCategory.bad,
    'com.kiloo.subwaysurf': AppCategory.bad,
    'com.imangi.templerun': AppCategory.bad,

    // === NEUTRAL (utility, communication) ===
    'com.google.android.apps.maps': AppCategory.neutral,
    'com.spotify.music': AppCategory.neutral,
    'com.google.android.apps.youtube.music': AppCategory.neutral,
    'com.apple.android.music': AppCategory.neutral,
    'com.whatsapp': AppCategory.neutral,
    'com.google.android.apps.messaging': AppCategory.neutral,
    'com.android.dialer': AppCategory.neutral,
    'com.google.android.gm': AppCategory.neutral,       // Gmail
    'com.microsoft.outlook': AppCategory.neutral,
    'com.google.android.calendar': AppCategory.neutral,
    'com.weather.Weather': AppCategory.neutral,
    'com.yahoo.mobile.client.android.weather': AppCategory.neutral,
    'com.google.android.apps.photos': AppCategory.neutral,
    'com.google.android.apps.docs': AppCategory.neutral,
    'com.netflix.mediaclient': AppCategory.neutral,
    'com.amazon.avod.thirdpartyclient': AppCategory.neutral, // Prime Video
    'com.hulu.plus': AppCategory.neutral,
    'com.disney.disneyplus': AppCategory.neutral,
    'com.google.android.youtube': AppCategory.neutral,
    'com.slack': AppCategory.neutral,
    'com.microsoft.teams': AppCategory.neutral,
    'us.zoom.videomeetings': AppCategory.neutral,
    'com.skype.raider': AppCategory.neutral,
    'org.telegram.messenger': AppCategory.neutral,
    'com.discord': AppCategory.neutral,
  };
}
